apiVersion: v1
kind: Service
metadata:
  name: persistencia-service
spec:
  type: NodePort
  selector:
    app: persistencia
  ports:
    - port: 80           # porta interna do service
      targetPort: 80   # porta que o container est√° ouvindo 
      nodePort: 30081    # porta exposta fora do cluster
